FROM rocker/shiny:4.4.3

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libgdal-dev \
    libgeos-dev \
    libproj-dev \
    libudunits2-dev \
    libssl-dev \
    libcurl4-openssl-dev

# Install R packages
RUN R -e "install.packages(c('shinydashboard','plotly','leaflet','ggplot2','dplyr','DT','terra','lidR','sf','RCSF'), repos='https://cran.r-project.org/')"

# Copy app
COPY app.R /srv/shiny-server/app/app.R
COPY Data /srv/shiny-server/app/Data

EXPOSE 3838

CMD ["/usr/bin/shiny-server"]